// <auto-generated />
using System;
using Auction_House.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auction_House.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Auction_House.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Auction_House.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuctionStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCategory")
                        .HasColumnType("int");

                    b.Property<int>("ItemCondition")
                        .HasColumnType("int");

                    b.Property<double>("MinimumBid")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuctionEnd = new DateTime(2023, 3, 14, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2142),
                            AuctionStart = new DateTime(2023, 2, 22, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2102),
                            Description = "The controller features a predominantly white color scheme, with black accents and a green Xbox logo button in the center. It has two thumbsticks, a directional pad, four face buttons, two triggers, two bumpers, and a set of menu buttons. The controller connects wirelessly to the Xbox console or PC using Bluetooth technology, and it requires two AA batteries for power. The white Xbox controller is a popular accessory for gamers who prefer a classic design and a comfortable, responsive gaming experience.",
                            ImageURL = "/img/xboxcontroller.jpg",
                            ItemCategory = 0,
                            ItemCondition = 0,
                            MinimumBid = 39.5,
                            Name = "Xbox Controller"
                        },
                        new
                        {
                            Id = -2,
                            AuctionEnd = new DateTime(2023, 3, 7, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2147),
                            AuctionStart = new DateTime(2023, 3, 4, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2145),
                            Description = " specialized chair designed for gamers who spend long hours playing video games. These chairs are typically designed with comfort and support in mind, and are often highly adjustable to fit the needs of individual users.",
                            ImageURL = "/img/gamerchair.jpg",
                            ItemCategory = 6,
                            ItemCondition = 2,
                            MinimumBid = 29.5,
                            Name = "Gaming Chair"
                        },
                        new
                        {
                            Id = -3,
                            AuctionEnd = new DateTime(2023, 3, 7, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2151),
                            AuctionStart = new DateTime(2023, 3, 4, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2150),
                            Description = "This high-quality backpack is an essential accessory for anyone on-the-go. It boasts durable materials, multiple compartments, and specialized features such as padded straps or water-resistant materials. Available in various styles, colors, and patterns to suit individual preferences, this backpack is a practical and stylish choice for everyday use or outdoor adventures. Shop now to experience the comfort and convenience of this versatile accessory!",
                            ImageURL = "/img/backpack.jpg",
                            ItemCategory = 2,
                            ItemCondition = 0,
                            MinimumBid = 29.5,
                            Name = "Backpack"
                        },
                        new
                        {
                            Id = -4,
                            AuctionEnd = new DateTime(2023, 3, 7, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2155),
                            AuctionStart = new DateTime(2023, 3, 4, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2154),
                            Description = "Experience exceptional sound quality and stylish design with these Beats headphones. The headphones feature high-quality sound drivers, noise-cancelling technology, and Bluetooth connectivity for seamless wireless use. The sleek design is available in various colors to suit individual preferences, and the headphones come with a convenient carrying case for on-the-go use. Whether you're listening to music or taking calls, these Beats headphones deliver exceptional sound and style. Shop now to experience the ultimate in headphone technology!",
                            ImageURL = "/img/beats.jpg",
                            ItemCategory = 0,
                            ItemCondition = 2,
                            MinimumBid = 29.5,
                            Name = "Beats"
                        },
                        new
                        {
                            Id = -5,
                            AuctionEnd = new DateTime(2023, 3, 7, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2159),
                            AuctionStart = new DateTime(2023, 3, 4, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2158),
                            Description = "Illuminate your workspace with this stylish and functional desk lamp. Featuring adjustable brightness levels and color temperature, this lamp provides the perfect lighting for any task. The sleek design is perfect for modern or traditional decor, and the lamp is made with high-quality materials for durability and long-lasting use. Whether you're working late into the night or need a focused light for reading, this desk lamp is the perfect solution. Shop now to enhance your productivity and workspace!",
                            ImageURL = "/img/desklamp.jpg",
                            ItemCategory = 6,
                            ItemCondition = 0,
                            MinimumBid = 29.5,
                            Name = "Desk Lamp"
                        },
                        new
                        {
                            Id = -6,
                            AuctionEnd = new DateTime(2023, 3, 7, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2163),
                            AuctionStart = new DateTime(2023, 3, 4, 20, 37, 5, 395, DateTimeKind.Local).AddTicks(2162),
                            Description = "Stay comfortable and stylish with this grey hoodie. Made with high-quality materials, this hoodie is soft, warm, and perfect for everyday wear. The classic design features a comfortable fit, drawstring hood, and kangaroo pocket for added convenience. The neutral grey color is perfect for pairing with any outfit, and the hoodie is available in various sizes to suit individual preferences. Whether you're lounging at home or running errands, this grey hoodie is the perfect choice for comfort and style. Shop now to upgrade your wardrobe!",
                            ImageURL = "/img/hoodie.jpg",
                            ItemCategory = 2,
                            ItemCondition = 0,
                            MinimumBid = 29.5,
                            Name = "Hoodie"
                        });
                });

            modelBuilder.Entity("Auction_House.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Bio = "This is the Bio of the first seller",
                            FullName = "Billy Butcher"
                        },
                        new
                        {
                            Id = -2,
                            Bio = "This is the Bio of the second seller",
                            FullName = "John Wick"
                        });
                });

            modelBuilder.Entity("Auction_House.Models.Seller_Item", b =>
                {
                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("SellerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Sellers_Items");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Auction_House.Models.Seller_Item", b =>
                {
                    b.HasOne("Auction_House.Models.Item", "Item")
                        .WithMany("Seller_Items")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auction_House.Models.Seller", "Seller")
                        .WithMany("Seller_Items")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Auction_House.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Auction_House.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auction_House.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Auction_House.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auction_House.Models.Item", b =>
                {
                    b.Navigation("Seller_Items");
                });

            modelBuilder.Entity("Auction_House.Models.Seller", b =>
                {
                    b.Navigation("Seller_Items");
                });
#pragma warning restore 612, 618
        }
    }
}
